apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: devfile-sample-u0hi
spec:
  replicas: 1
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/pmacik-testing/tkrw-pr712-0075-0048-tenant/tkrw-pr712-0075-0048-app/devfile-sample-u0hi@sha256:28581d1ecd2cb1cd7c7a78f06b7f74cd3e42631df8d32f9921fb7b5e154f7810
        name: my-nodejs
        resources: {}
status: {}
